services:
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wg-easy
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=<HOST1_PUBLIC_IP_OR_DNS>
      - WG_PORT=51820
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=10.8.0.0/24
      - WG_ALLOWED_IPS_V6=
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEVICE=wg0
      - WG_MTU=1420
      - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT
      - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT
      - PASSWORD_HASH=<bcrypt_or_leave_blank>
      - PORT=51821
      - UI_TRAFFIC_STATS=true
    volumes:
      - /opt/wg-easy:/etc/wireguard
    restart: unless-stopped
