services:
  wg-hub:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wg-hub
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
    volumes:
      - /opt/wg-hub/config:/config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"}  }``` }
